<?
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/header.php');
$APPLICATION->SetTitle("Главная");
$APPLICATION->SetPageProperty('title', 'Digital агентство We coders');
?><br>
 <br>
 <br>
 <br>
 <br>
 <br>
 <br>
 <br>
 <br>
 <br>
 <br>
 <br>
 test<br>
<br><?
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/footer.php');
?>